### PR TITLE
Added wizard scene decorators & support multiple method listeners

### PR DESCRIPTION
**Pull request by xTCry**
Solution issue #414 with method listener chains.
Solution issue #350 with wizard scenes https://github.com/bukhalo/nestjs-telegraf/issues/350#issuecomment-877317009.

### CODE REVIEW

**Comment by viacheslav-saloid-happ** [comment]
@xTCry Thank you very much for this pr

Could you explain, how to navigate between steps? i didn't find a way to use wizard.next() or similar ?

**Comment by ghost** [comment]
@xTCry Thank you very muck of this pr. I tried - it's so cool

But, it was my fault. We can't use decorators for functions. So, it's not possible to use

```
@WizardStep(1)
step1() {
     
     @On('text') //  Decorators are not valid here.
     textHandler() { }
}
```

Maybe, the way is to use combined decorators? 


```
@WizardStep(1)
@On('text')
textHandlerForWizardStep1() {

}
```

**Comment by xTCry** [comment]
> Maybe, the way is to use combined decorators?
> 
> ```
> @WizardStep(1)
> @On('text')
> textHandlerForWizardStep1() {
> 
> }
> ```

@viacheslav-saloid-happ, Yes, that's right

Here is an imperfect example
```ts

@Wizard('buy')
@UseFilters(TelegrafExceptionFilter)
export class BuyCategoryScene {
    constructor(
        private readonly keyboardFactory: KeyboardFactory,
    ) {}

    @SceneLeave()
    async onLeave(@Context() ctx: IWizardContext) {
        // const keyboard = this.keyboardFactory.getProfile(ctx);
        // await ctx.replyWithHTML(ctx.i18n.t(LocalePhrase.Profile, ctx), keyboard);
    }

    @Command('cancel')
    @Action('cancel')
    @Action(LocalePhrase.Cancel_Button)
    @HearsLocale(KeyboardT.Cancel)
    async onСancel(@Context() ctx: IWizardContext) {
        const msg = ctx.i18n.t(LocalePhrase.Canceled);
        if (ctx.updateType === 'callback_query') {
            ctx.tryAnswerCbQuery(msg);
            await ctx.deleteMessage();
        } else {
            await ctx.replyWithHTML(msg);
        }
        ctx.scene.leave();
    }

    // @SceneEnter()
    @WizardStep(1)
    async step1(@Context() ctx: IWizardContext) {
        console.log('[step1] step', ctx.wizard.step);
        console.log('[step1] state', ctx.wizard.state);
        ctx.reply('step 1');

        const categoryId = Number((ctx.scene.state as any).categoryId);
        const category = await this.stockService.getCategoryById(categoryId);

        ctx.scene.state.categoryId = categoryId;

        ctx.replyWithHTML(ctx.i18n.t(LocalePhrase.StockOrderInfo, { ...ctx, category }));
        ctx.wizard.next();
    }

    // @Hears(/^(?<count>\d+)/)
    @WizardStep(2)
    @Hears(/.+/)
    async hearCount(@Context() ctx: IWizardContext) {
        ctx.reply('step 2');
        // const count = Number(ctx.match.groups.count);
        const count = Number(ctx.message.text);
        if (isNaN(count) || count < 1) {
            ctx.replyWithHTML(ctx.i18n.t(LocalePhrase.WrongPositiveNumber));
            return;
        }
        // ...

        ctx.wizard.next();
    }

    @WizardStep(3)
    @Action('so_buy')
    @Transactional()
    async step3(@Context() ctx: IWizardContext) {
        ctx.reply('step 3.1');
        const { categoryId, count, totalPriceUSD } = ctx.scene.state;

        if (totalPriceUSD > ctx.user.balanceUSD) {
            ctx.replyWithHTML(ctx.i18n.t(LocalePhrase.StockNotEnoughBalance, { ...ctx, totalPriceUSD }));
            ctx.scene.leave();
            return;
        }
        // ...

        ctx.scene.leave();
    }

    @WizardStep(3)
    @Action('three')
    @Hears('three')
    async step3_2(@Context() ctx: IWizardContext) {
        ctx.reply('step 3.2');
    }

    @Hears('ping')
    async hearPing(@Context() ctx: IWizardContext) {
        ctx.reply('PONG');
    }
}
```

But first you need to wait for the merge to the master branch

**Comment by MyWay** [comment]
Good job! Hope to see it merged soon!

**Review by evilsprut — APPROVED** [review]

**Comment by StackTraceYo** [comment]
Can we see an example with the callback data from a button in a wizard?

**Pull request merged**
