### PR TITLE
Feature/v2

### PR DESCRIPTION
**Pull request by Morb0**
Hi, I recently needed a lot of work with Telegram and I found your library, it's good, thank you for it.

I saw that it was planned to transfer to the new version of the Telegraf and add many convenient features and I decided to add them to the library myself. It came out too globally and therefore I don't even know if you need it.
I would like to hear your opinion on this. If you decide to take these changes, you can point out places in the code that seems to you to be incorrect and we could fix everything.
You can also take notes on which I can give explanations, because the new version of the telegraf turned out to have a lot of controversial points (for example, as types).

Current improvements:
- Uses "dev" Telegraf branch
- Middleware support
- Scene support
- Dynamic typing for listeners

### CODE REVIEW

**Comment by evilsprut** [comment]
Wow! Cool job @Morb0! I'll take a close look at the PR and come back with an answer soon.

**Comment by evilsprut** [comment]
@Morb0, documentation for the new functionality is also needed.

**Comment by Morb0** [comment]
okay, I'll start doing this.

**Comment by evilsprut** [comment]
@Morb0 write me at https://telegram.me/bukhalo_a If you have some time

**Pull request merged**
